=== skuranov/XMLReader/StudentsReport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.com/StudentsReport" xmlns:tns="http://www.epam.com/StudentsReport" elementFormDefault="qualified">

    <include schemaLocation=""></include>
    
    <element name="teachingCenter" type="tns:teachingCenter">
	    <unique name="uniqueStudent">
	      <selector xpath="tns:students/tns:student"/>
	      <field xpath="@email"/>
	      <field xpath="@fullName"/>
	    </unique>
 	   
	    <key name="pCourseName">
	      <selector xpath="tns:courses/tns:course"/>
	      <field xpath="@courseName"/>
    	</key>

	    <keyref name="pCourseNameRef" refer="tns:pCourseName">
	      <selector xpath="tns:programs/tns:program/tns:courseName"/>
	      <field xpath="@courceName"/>
	    </keyref>
	    
	    <!--Synchronizing student programs -->
	    
	    <key name="uniqueFullProgramName">
	      <selector xpath="tns:programs/tns:fullProgram/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <key name="uniqueShortProgramName">
	      <selector xpath="tns:programs/tns:shortProgram/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <key name="uniqueSpecialProgram1Name">
	      <selector xpath="tns:programs/tns:specialProgram1/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <key name="FullProgramName">
	      <selector xpath="tns:programs/tns:fullProgram"/>
	      <field xpath="@programName"/>
	    </key>
	    
	    <key name="ShortProgramName">
	      <selector xpath="tns:programs/tns:shortProgram"/>
	      <field xpath="@programName"/>
	    </key>
	    
	    <key name="SpecialProgram1Name">
	      <selector xpath="tns:programs/tns:specialProgram1"/>
	      <field xpath="@programName"/>
	    </key>
	    
	    <keyref name="FullProgramNameRef" refer="tns:FullProgramName">
	      <selector xpath="tns:students/tns:student/tns:fullProgram"/>
	      <field xpath="@programName"/>
	    </keyref>
	    
	    <keyref name="ShortProgramNameRef" refer="tns:ShortProgramName">
	      <selector xpath="tns:students/tns:student/tns:shortProgram"/>
	      <field xpath="@programName"/>
	    </keyref>
	    
	    <keyref name="SpecialProgram1NameRef" refer="tns:SpecialProgram1Name">
	      <selector xpath="tns:students/tns:student/tns:specialProgram1"/>
	      <field xpath="@programName"/>
	    </keyref>
	    
	     <!--Synchronizing student courses -->
	    
	    <key name="uniqueFullProgramCourse">
	      <selector xpath="tns:programs/tns:fullProgram/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <key name="uniqueShortProgramCourse">
	      <selector xpath="tns:programs/tns:shortProgram/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <key name="uniqueSpecialProgram1Course">
	      <selector xpath="tns:programs/tns:specialProgram1/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <key name="FullProgramCourse">
	      <selector xpath="tns:programs/tns:fullProgram/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <key name="ShortProgramCourse">
	      <selector xpath="tns:programs/tns:shortProgram/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <key name="SpecialProgram1Course">
	      <selector xpath="tns:programs/tns:specialProgram1/tns:course"/>
	      <field xpath="@courseName"/>
	    </key>
	    
	    <keyref name="FullProgramCourseRef" refer="tns:FullProgramCourse">
	      <selector xpath="tns:students/tns:student/tns:fullProgram/tns:course"/>
	      <field xpath="@courseName"/>
	    </keyref>
	    
	    <keyref name="ShortProgramCourseRef" refer="tns:ShortProgramCourse">
	      <selector xpath="tns:students/tns:student/tns:shortProgram/tns:course"/>
	      <field xpath="@courseName"/>
	    </keyref>
	    
	    <keyref name="SpecialProgram1CourseRef" refer="tns:SpecialProgram1Course">
	      <selector xpath="tns:students/tns:student/tns:specialProgram1/tns:course"/>
	      <field xpath="@courseName"/>
	    </keyref>
	    
	    
	    <!--Synchronizing tasks -->
	 
	    <key name="theoryTaskKey">
	      <selector xpath="tns:courses/tns:course/tns:theoryTask"/>
	      <field xpath="@taskName"/>
	      <field xpath="@taskId"/>
	    </key>
	    
	    <key name="practicalTaskKey">
	      <selector xpath="tns:courses/tns:course/tns:practicalTask"/>
	      <field xpath="@taskName"/>
	      <field xpath="@taskId"/>
	    </key>
	       
	    <keyref name="theoryTaskRef" refer="tns:theoryTaskKey">
	      <selector xpath="tns:students/tns:student/tns:courses/tns:cource/tns:theoryTask"/>
	      <field xpath="@taskName"/>
	      <field xpath="@taskId"/>
	    </keyref>
	    
	    <keyref name="practicalTaskRef" refer="tns:practicalTaskKey">
	      <selector xpath="tns:students/tns:student/tns:courses/tns:cource/tns:practicalTask"/>
	      <field xpath="@taskName"/>
	      <field xpath="@taskId"/>
	    </keyref>

    </element>

    <complexType name="teachingCenter">
    	<sequence>
    		<element name="courses" type="tns:coursesType"></element>
    		<element name="programs" type="tns:programsType"></element>
    		<element name="students" type="tns:studentsType"></element>
    	</sequence>
    </complexType>

    <complexType name="coursesType">
    	<sequence><element name="course" type="tns:courseType" maxOccurs="unbounded" minOccurs="0"></element></sequence>
    </complexType>

    <complexType name="programsType">
    	<sequence>
    		<element name="fullProgram" type="tns:fullProgram"></element>
    		<element name="shortProgram" type="tns:shortProgram"></element>
    		<element name="specialProgram1"
    			type="tns:specialProgram1">
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="studentsType">
    	<sequence>
    		<element name="student" type="tns:studentType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    
    <complexType name="studentType">
    	<sequence>
    		<choice>
    			<element name="fullProgram" type="tns:fullProgram"></element>
    			<element name="shortProgram" type="tns:shortProgram"></element>
    			<element name="specialProgram1"
    				type="tns:specialProgram1">
    			</element>
    		</choice>
    	</sequence>
    	<attribute name="fullName" type="tns:shortString"></attribute>
    	<attribute name="city" type="tns:shortString"></attribute>
    	<attribute name="email" type="tns:e-mail"></attribute>
    	<attribute name="startDate" type="date"></attribute>
    	<attribute name="signedContract" type="boolean"></attribute>
    </complexType>

    <complexType name="courseType">
    	<sequence>
    		<element name="theoryTask" type="tns:theoryTask" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="practicalTask" type="tns:practicalTask" maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="courseName" type="tns:shortString"></attribute>
    	<attribute name="author" type="tns:shortString"></attribute>
    	<attribute name="birthDate" type="date"></attribute>
    </complexType>

    <simpleType name="shortString">
    	<restriction base="string">
    		<pattern value=".{1,70}"/>
    	</restriction>
    </simpleType>

    <simpleType name="e-mail">
    	<restriction base="string">
    		<pattern value=".+\@.+\..+"/>
    	</restriction>
    </simpleType>

    <simpleType name="theoryTaskStatus">
    	<restriction base="string">
    		<enumeration value="изучение не началось"></enumeration>
    		<enumeration value="в процессе изучения"></enumeration>
    		<enumeration value="изучение завершено"></enumeration>
    	</restriction>
    </simpleType>
    
    <simpleType name="practicalTaskStatus">
    	<restriction base="string">
    		<enumeration value="выполнение не началось"></enumeration>
    		<enumeration value="в процессе выполнения"></enumeration>
    		<enumeration value="находится на проверке"></enumeration>
    		<enumeration value="задание принято"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="markType">
    	<restriction base="integer">
    		<minInclusive value="1"/>
    		<maxInclusive value="5"/>
    	</restriction>
    </simpleType>

    <complexType name="courseNameType">
    	<sequence>
    	</sequence>
    	<attribute name="courceName" type="tns:shortString"></attribute>
    </complexType>


    <complexType name="theoryTask">
    	<attribute name="status" type="tns:theoryTaskStatus"></attribute>
    	<attribute name="taskName" type="tns:shortString"></attribute>
    	<attribute name="planTime" type="int"></attribute>
    	<attribute name="taskId" type="int"></attribute>
    	<attribute name="mark" type="tns:markType"></attribute>
    </complexType>

    <complexType name="practicalTask">
   		<attribute name="status" type="tns:practicalTaskStatus"></attribute>
    	<attribute name="taskName" type="tns:shortString"></attribute>
    	<attribute name="planTime" type="int"></attribute>
    	<attribute name="taskId" type="int"></attribute>
    	<attribute name="mark" type="tns:markType"></attribute>
    </complexType>


    <complexType name="fullProgram">
    	<sequence>
            <element name="course" type="tns:courseType" maxOccurs="unbounded" minOccurs="0">
    		</element>
        </sequence>
    	<attribute name="programName" type="tns:shortString"></attribute>
    	<attribute name="author" type="tns:shortString"></attribute>
    	<attribute name="birthDate" type="date"></attribute>
    </complexType>
    
    <complexType name="shortProgram">
    	<sequence>
    		<element name="course" type="tns:courseType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		
        </sequence>
    	<attribute name="programName" type="tns:shortString"></attribute>
    	<attribute name="author" type="tns:shortString"></attribute>
    	<attribute name="birthDate" type="date"></attribute>
    </complexType>
    
    <complexType name="specialProgram1">
    	<sequence>
    		<element name="course" type="tns:courseType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="programName" type="tns:shortString"></attribute>
    	<attribute name="author" type="tns:shortString"></attribute>
    	<attribute name="birthDate" type="date"></attribute>
    </complexType>
</schema>

=== skuranov/XMLReader/Report.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:teachingCenter xmlns:tns="http://www.epam.com/StudentsReport" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.epam.com/StudentsReport StudentsReport.xsd ">
  <tns:courses>
    <tns:course author="Ivan Ivanov" birthDate="2010-08-31" courseName="Курс &quot;Overview of Eclipse IDE&quot;">
      <tns:theoryTask planTime="4" taskName="Overview of Eclipse IDE" taskId="1"/>  
    </tns:course>
    <tns:course author="Petr Petrov" birthDate="2010-08-31" courseName="Курс &quot;Основы языка Java&quot;">
      <tns:theoryTask planTime="12" taskName="Learning the Java Language Basics" taskId="2"/>
      <tns:practicalTask planTime="12" taskName="Practical Task" taskId="3"/>
    </tns:course>
    <tns:course author="Sidor Sidorov" birthDate="2010-08-31" courseName="Курс &quot;Язык Java - расширенные возможности&quot;">
      <tns:theoryTask planTime="17" taskName="Learning the Java Language advanced features" taskId="4"/>
      <tns:practicalTask planTime="16" taskName="Practical Task" taskId="5"/>
    </tns:course>
    <tns:course author="Ivan Ivanov" birthDate="2010-08-31" courseName="Курс &quot;Язык XML&quot;">
      <tns:theoryTask planTime="6" taskName="Learning XML Language" taskId="6"/>
      <tns:practicalTask planTime="8" taskName="Practical Task" taskId="7"/>
    </tns:course>
    <tns:course author="Petr Petrov" birthDate="2010-08-31" courseName="Курс &quot;Язык XSLT и XPath&quot;">
      <tns:theoryTask planTime="14" taskName="Learning XSLT and XPath Basics" taskId="8"/>
      <tns:practicalTask planTime="8" taskName="Equipment Stylesheets" taskId="9"/>
    </tns:course>
    <tns:course author="Sidor Sidorov" birthDate="2010-08-31" courseName="Курс &quot;Технология Struts Framework&quot;">
      <tns:theoryTask planTime="8" taskName="Struts Framework Fundamentals" taskId="10"/>
      <tns:practicalTask planTime="40" taskName="Struts Framework Task" taskId="11"/>
      <tns:practicalTask planTime="20" taskName="Java Message Service Task" taskId="12"/>
    </tns:course>
    <tns:course author="Ivan Ivanov" birthDate="2010-08-31" courseName="Курс &quot;Процесс производства программного обеспечения&quot;">
      <tns:theoryTask planTime="3" taskName="Mastering Microsoft Project" taskId="13"/>
      <tns:practicalTask planTime="8" taskName="MS Project Practical Task" taskId="14"/>
      <tns:practicalTask planTime="12" taskName="Software development process. Development team and its structure" taskId="15"/>
    </tns:course>
    <tns:course author="Petr Petrov" birthDate="2010-08-31" courseName="Курс &quot;Процесс разработки программного обеспечения&quot;">
      <tns:practicalTask planTime="80" taskName="Team Project" taskId="16"/>
    </tns:course>
  </tns:courses>
  <tns:programs>
    <tns:fullProgram author="Ivan Ivanov" birthDate="2010-08-31" programName="Полная программа">
      <tns:course courseName="Курс &quot;Overview of Eclipse IDE&quot;"/>
      <tns:course courseName="Курс &quot;Основы языка Java&quot;"/>
      <tns:course courseName="Курс &quot;Язык Java - расширенные возможности&quot;"/>
      <tns:course courseName="Курс &quot;Язык XML&quot;"/>
      <tns:course courseName="Курс &quot;Язык XSLT и XPath&quot;"/>
      <tns:course courseName="Курс &quot;Технология Struts Framework&quot;"/>
      <tns:course courseName="Курс &quot;Процесс производства программного обеспечения&quot;"/>
      <tns:course courseName="Курс &quot;Процесс разработки программного обеспечения&quot;"/>
    </tns:fullProgram>
    <tns:shortProgram author="Ivan Ivanov" birthDate="2010-08-31" programName="Укороченная программа">
      <tns:course courseName="Курс &quot;Overview of Eclipse IDE&quot;"/>
      <tns:course courseName="Курс &quot;Основы языка Java&quot;"/>
      <tns:course courseName="Курс &quot;Язык Java - расширенные возможности&quot;"/>
      <tns:course courseName="Курс &quot;Процесс производства программного обеспечения&quot;"/>
      <tns:course courseName="Курс &quot;Процесс разработки программного обеспечения&quot;"/>
    </tns:shortProgram>
    <tns:specialProgram1 author="Sidor Sidorov" birthDate="2013-12-03" programName="Специальная программа 1">
      <tns:course courseName="Курс &quot;Язык XML&quot;"/>
      <tns:course courseName="Курс &quot;Язык XSLT и XPath&quot;"/>
    </tns:specialProgram1>
  </tns:programs>
 <tns:students>
    <tns:student city="Saratov" email="alexander_sergeev@epam.com" fullName="Alexander Sergeev" signedContract="true" startDate="2015-08-15">
      <tns:fullProgram programName="Полная программа">	
        <tns:course courseName="Курс &quot;Overview of Eclipse IDE&quot;">
          <tns:theoryTask planTime="4" status="изучение завершено" taskName="Overview of Eclipse IDE" taskId="1"/>  
        </tns:course>
        <tns:course courseName="Курс &quot;Основы языка Java&quot;">
          <tns:theoryTask mark="5" status="изучение завершено" taskName="Learning the Java Language Basics" taskId="2"/>
          <tns:practicalTask status="выполнение не началось" taskName="Practical Task" taskId="3"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Язык Java - расширенные возможности&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Learning the Java Language advanced features" taskId="4"/>
          <tns:practicalTask status="выполнение не началось" taskName="Practical Task" taskId="5"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Язык XML&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Learning XML Language" taskId="6"/>
          <tns:practicalTask status="выполнение не началось" taskName="Practical Task" taskId="7"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Язык XSLT и XPath&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Learning XSLT and XPath Basics" taskId="8"/>
          <tns:practicalTask status="выполнение не началось" taskName="Equipment Stylesheets" taskId="9"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Технология Struts Framework&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Struts Framework Fundamentals" taskId="10"/>
          <tns:practicalTask status="выполнение не началось" taskName="Struts Framework Task" taskId="11"/>
          <tns:practicalTask status="выполнение не началось" taskName="Java Message Service Task" taskId="12"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Процесс производства программного обеспечения&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Mastering Microsoft Project" taskId="13"/>
          <tns:practicalTask status="выполнение не началось" taskName="MS Project Practical Task" taskId="14"/>
          <tns:practicalTask status="выполнение не началось" taskName="Software development process. Development team and its structure" taskId="15"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Процесс разработки программного обеспечения&quot;">
          <tns:practicalTask status="выполнение не началось" taskName="Team Project" taskId="16"/>
        </tns:course>
      </tns:fullProgram>
    </tns:student>
    <tns:student city="Moskow" email="boris_romanov@epam.com" fullName="Boris Romanov" signedContract="false" startDate="2015-09-01">
      <tns:fullProgram programName="Полная программа">	
        <tns:course courseName="Курс &quot;Overview of Eclipse IDE&quot;">
          <tns:theoryTask mark="1" status="изучение завершено" taskName="Overview of Eclipse IDE" taskId="1"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Основы языка Java&quot;">
          <tns:theoryTask status="изучение завершено" taskName="Learning the Java Language Basics" taskId="2"/>
          <tns:practicalTask status="выполнение не началось" taskName="Practical Task" taskId="3"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Язык Java - расширенные возможности&quot;">
          <tns:theoryTask mark="5" status="изучение не началось" taskName="Learning the Java Language advanced features" taskId="4"/>
          <tns:practicalTask mark="5" status="выполнение не началось" taskName="Practical Task" taskId="5"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Язык XML&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Learning XML Language" taskId="6"/>
          <tns:practicalTask status="выполнение не началось" taskName="Practical Task" taskId="7"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Язык XSLT и XPath&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Learning XSLT and XPath Basics" taskId="8"/>
          <tns:practicalTask status="выполнение не началось" taskName="Equipment Stylesheets" taskId="9"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Технология Struts Framework&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Struts Framework Fundamentals" taskId="10"/>
          <tns:practicalTask status="выполнение не началось" taskName="Struts Framework Task" taskId="11"/>
          <tns:practicalTask status="выполнение не началось" taskName="Java Message Service Task" taskId="12"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Процесс производства программного обеспечения&quot;">
          <tns:theoryTask status="изучение не началось" taskName="Mastering Microsoft Project" taskId="13"/>
          <tns:practicalTask status="выполнение не началось" taskName="MS Project Practical Task" taskId="14"/>
          <tns:practicalTask status="выполнение не началось" taskName="Software development process. Development team and its structure" taskId="15"/>
        </tns:course>
        <tns:course courseName="Курс &quot;Процесс разработки программного обеспечения&quot;">
          <tns:practicalTask status="выполнение не началось" taskName="Team Project" taskId="16"/>
